services:

  app-service:
    build: .
    container_name: knowledge_testing_app
    ports:
      - "8000:8000"
    networks:
      - app_newtwork


  db-service:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_newtwork

networks:
  app_newtwork:

volumes:
  postgres_data: